商品情報編集機能の実装
atsushikitamura/furima-35862 pull request #7
Opened 2021-06-23 13:12 UTC by atsushikitamura

# What
商品情報編集機能の実装

# Why
商品情報編集機能を実装するため

2021-06-23 13:32 UTC, atsushikitamura commented
レビューをよろしくお願いいたします！

Gyazo URL↓
https://gyazo.com/cc4c5a6dd22fad33ab5cf046b5dafce7
https://gyazo.com/8bf822b0b10f960f1f93e068c2b23565
https://gyazo.com/a51824fd17296e50d8ce2522149ed726
https://gyazo.com/0acd4e6e2c7d93580f9de5b7a382a077
https://gyazo.com/d36dd85d38fc8b2512ce8d3203722ef2

https://gyazo.com/81e9cab7939b9f1b663e0ef05f04461f
https://gyazo.com/b1b23e0f476f72404fb4809ce172f594

2021-06-24 02:14 UTC, mihot117 reviewed
レビュー依頼ありがとうございます！

コメントいたしましたので、ご確認をお願いいたします。

コードの修正後、コミット・プッシュを行った上で再度レビュー依頼をお送りください。
お手数をお掛け致しますが、よろしくお願いいたします。

2021-06-24 02:14 UTC, mihot117 commented on app/controllers/items_controller.rb
> +  before_action :move_to_index, only: [:destroy, :edit, :create]
```ruby
before_action :set_item, only: [:show, :destroy, :edit]
before_action :move_to_index, only: [:destroy, :edit, :create]
```

上記のアクションですが、4行目の`:create`アクションは削除いただいて問題ないかと存じます！

`出品者がログインユーザーだったらトップページへリダイレクトさせる`という条件分岐を`create`アクションで適用させる必要がないためです。

ただし、`update`アクションに関しましては上記を適用させる必要がございますので、before_action内の修正をお願いいたします。

#### updateアクションを追加いただく理由：
セキュリティ面を強化するためです。
create、update、destroyアクションは、今回のFURIMAにおいて対応するビューファイルがなく（create.html.erbなど）、一見不正なアクセスができないように思える処理ですが、「検証ツールからボタンを表示させる」「URLの直接入力をする」といった行為で不正なアクセスができてしまうことがあるためです。

2021-06-24 02:14 UTC, mihot117 commented on app/views/items/edit.html.erb
>          </div>
こちらは任意での修正となります！

142行目に下記の記述がございます。
こちらは、詳細ページに戻れるようなパスを設定いただくコードになっております。
戻るボタンが押せる仕様になっている方が使いやすさが増しますので、コードの修正をお願いいたします。

```ruby
<%=link_to 'もどる', "#", class:"back-btn" %>
```

2021-06-24 02:50 UTC, atsushikitamura commented
コメントが、今までで一番分かりやすかったです！
ありがとうございます！

訂正と動作確認が終わりましたので、再度レビューをお願いいたします！

2021-06-24 02:57 UTC, Saka-toku requested changes
レビュー依頼ありがとうございます！
修正点を確認させていただきました。
1点コメントいたしましたので、ご確認お願いいたします！

2021-06-24 02:57 UTC, Saka-toku commented on app/controllers/items_controller.rb
> +  before_action :set_item, only: [:show, :destroy, :edit]
`  before_action :set_item, only: [:show, :destroy, :edit]`
上記のonlyオプションにupdateアクションを追加しましょう。
そのあとupdateアクション内にある@`item = Item.find(params[:id])`は削除をお願いいたします。

2021-06-24 03:08 UTC, atsushikitamura commented
訂正いたしましたので、再度レビューをお願いいたします。

2021-06-24 03:10 UTC, Saka-toku commented
レビュー依頼ありがとうございます！
編集機能の実装ですがLGTMとさせていただきます！
実装お疲れさまでした！！

マージ後、ローカルのmasterブランチでプルをお願いいたします。
その後masterブランチから新たなブランチを作成し、次の実装に取り組んでいただけますと幸いです。
次の実装も頑張っていきましょう！

2021-06-24 03:16 UTC, merged